version: '3.4'

services:
  mongo_db:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  product_catalog_services:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}